A.yarabaeva
GraphLabsSuite/Core.GraphVisualizer pull request #48
Opened 2021-04-24 14:33 UTC by ayarabaeva

2021-04-25 09:53 UTC, AMusatova approved these changes

2021-04-26 14:49 UTC, svtz requested changes

2021-04-26 14:49 UTC, svtz commented on src/adapters/ReadableAdapter.tsx
> +        } else if (this.props.weightNamedEdges == true) {
простыня из if-else-if-else.... смущает
Нужно общие части вынести в одно место. А в блоках if-else менять только то что реально различается. Как минимум `x` и `y` и `z-index` у них у всех одинаковые, шрифт, на первый взгляд, тоже должен быть один и тот же (хотя в последнем блоке он почему-то 15 вместо 16px)

2021-04-26 14:49 UTC, svtz commented on src/adapters/ReadableAdapter.tsx
> +                // .text(this.getAttribute('label')+'(' + this.getAttribute('wave') + ')');
давайте удалим закомментированный код

2021-04-26 14:49 UTC, svtz commented on src/adapters/ReadableAdapter.tsx
> +                .attr('id', `weightLabel_${elem.weightLabel}_${elem.edge.vertexOne.name}_${elem.edge.vertexTwo.name}`)
вот эти сложные дублирующиеся по всему коду правила составления id в зависимости от weighted/named/edges заслуживают быть вынесенными в отдельный метод

2021-04-26 15:12 UTC, ayarabaeva commented on src/adapters/ReadableAdapter.tsx
> +        } else if (this.props.weightNamedEdges == true) {
Там где 15, там просто больше текста вида: (a,1)  -поэтому шрифт уменьшила

2021-04-26 15:43 UTC, merged